### ISSUE TITLE
Hope to support gemini

### ISSUE THREAD

**Issue by Stanley-baby** [Eladlev/AutoPrompt#39]
1. gemini has a free usage quota
2. Convenient for users without OpenAI api
> Although OpenAI is currently the most cutting-edge llm, there is no doubt that using gemini can lower the threshold for use

**Comment by Eladlev** [comment]
Hi,
Adding LLMs that are supported by langchain, is simple I've attached a PR specifically on googe_genai.
In order to use Gemini you need to modify the config file:
`llm:
    type: 'Google'
    name: 'gemini-pro'`

One last thing, since Gemini doesn't support functions, you need to change the prompts path to the completion type:
`meta_prompts:
    folder: 'prompts/meta_prompts_completion'` 

We will soon add documentation on using the system with non-OpenAI models.
